print("Enter Details : ")
print("First Name : ",end="")
fn=input()
print("Last Name : ",end="")
ln=input()
print("Contact : ",end="")
num=input()
address=input("Address : ")
print("\n")
print("Full Name : ",fn," ",ln)
print("Contact : ",num)
print("Address : ",address)
